### PR TITLE
Fixed mersenne_twister:random() to return [0,1) instead of [0,0.5)

### PR DESCRIPTION
**Pull request by jminor**
I added some code to `demo.lua` which prints the min/max and histogram of results from calling `:random()` on each generator 10,000 times. In doing so, I noticed that `mersenne_twister:random()` was returning only results between 0 and 0.5, instead of between 0 and 1. This PR fixes that bug.

p.s. I made sure to update the copy of randomlua.lua inside the .love archive also.

### CODE REVIEW

**Comment by linux-man** [comment]
This was a long-time bug, probably created when I tried to force 32 bits output and never corrected.
Unfortunately, I wasn't able to merge your Histogram alone.
I didn't want to merge your random() fix because:

- I noticed that all other random() output were [0,1]. Fixed.
- Your love file was badly formatted.

So sorry for not accepting you commit, but credit to whom credit due. Thank you.

**Comment by linux-man** [comment]
.

**Comment by jminor** [comment]
That's fine. I'm glad my fix was helpful.

Out of curiosity, what was badly formatted about the love archive?

**Comment by linux-man** [comment]
It didn't launch. My guess is you compressed the folder when you must compress only the files within. Since I didn't save your fork and you already synchronized it I can't confirm.

**Comment by jminor** [comment]
Ok, thanks :)

**Pull request closed without merging**
